"""
MSSQL backup runner — exports databases as .sql script files via pyodbc.
Produces T-SQL compatible with SQL Server 2012+ and Azure SQL.
"""
import os
from datetime import datetime
from typing import Callable, List, Optional, Tuple

import pyodbc

from models.job import BackupJob

_DAYS = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]


def _safe_name(text: str) -> str:
    return "".join(c if c.isalnum() or c in "-_" else "_" for c in text)


def _conn_str(job: BackupJob, database: str = "master") -> str:
    server = f"{job.host},{job.port}" if job.port != 1433 else job.host
    base = f"DRIVER={{{job.mssql_driver}}};SERVER={server};DATABASE={database};TrustServerCertificate=yes;"
    if job.windows_auth:
        return base + "Trusted_Connection=yes;"
    return base + f"UID={job.username};PWD={job.password};"


class MSSQLBackupRunner:
    def __init__(self, job: BackupJob):
        self.job = job

    def run(self, progress: Optional[Callable[[str], None]] = None) -> Tuple[bool, str]:
        try:
            os.makedirs(self.job.output_dir, exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")

            if getattr(self.job, "mssql_backup_format", "sql") == "bak":
                return self._run_bak(ts, progress)

            if self.job.output_type == "daily_overwrite":
                return self._run_daily_overwrite(progress)
            if self.job.output_type == "multiple" and self.job.databases:
                return self._run_multiple(ts, progress)
            return self._run_single(ts, progress)
        except Exception as e:
            return False, f"MSSQL backup error: {e}"

    # ---------------------------------------------------------------- single --

    def _run_single(self, ts: str, progress: Optional[Callable]) -> Tuple[bool, str]:
        name = _safe_name(self.job.name)
        sql_path = os.path.join(self.job.output_dir, f"{name}_{ts}.sql")
        databases = self.job.databases

        if progress:
            progress(f"Exporting to {sql_path} …")

        try:
            conn = pyodbc.connect(_conn_str(self.job), timeout=10)
        except Exception as e:
            return False, f"Connection failed: {e}"

        try:
            with open(sql_path, "w", encoding="utf-8") as fh:
                fh.write("-- MSSQL backup generated by Database Backup Scheduler\n")
                fh.write(f"-- Date: {datetime.now()}\n\n")
                if not databases:
                    databases = self._list_databases(conn)
                for db in databases:
                    self._export_database(conn, db, fh, progress)
        finally:
            conn.close()

        if self.job.use_zip:
            return self._zip_file(sql_path, progress)
        return True, f"Saved: {sql_path}"

    # -------------------------------------------------------------- multiple --

    def _run_multiple(self, ts: str, progress: Optional[Callable]) -> Tuple[bool, str]:
        try:
            conn = pyodbc.connect(_conn_str(self.job), timeout=10)
        except Exception as e:
            return False, f"Connection failed: {e}"

        name = _safe_name(self.job.name)
        output_files: List[str] = []

        try:
            for db in self.job.databases:
                tables = self.job.tables.get(db, [])
                sql_path = os.path.join(self.job.output_dir, f"{name}_{db}_{ts}.sql")
                if progress:
                    progress(f"Exporting {db} → {sql_path}")
                with open(sql_path, "w", encoding="utf-8") as fh:
                    fh.write(f"-- MSSQL backup: {db}  Date: {datetime.now()}\n\n")
                    self._export_database(conn, db, fh, progress, tables_filter=tables)
                output_files.append(sql_path)
        finally:
            conn.close()

        if self.job.use_zip and output_files:
            return self._zip_files(output_files, ts, progress)
        return True, f"Backup complete — {len(output_files)} file(s)"

    # ---------------------------------------------------- daily overwrite --

    def _run_daily_overwrite(self, progress: Optional[Callable]) -> Tuple[bool, str]:
        day = _DAYS[datetime.now().weekday()]
        name = _safe_name(self.job.name)

        try:
            conn = pyodbc.connect(_conn_str(self.job), timeout=10)
        except Exception as e:
            return False, f"Connection failed: {e}"

        output_files: List[str] = []
        databases = self.job.databases or self._list_databases(conn)

        try:
            for db in databases:
                tables = self.job.tables.get(db, [])
                sql_path = os.path.join(self.job.output_dir, f"{name}_{db}_{day}.sql")
                if progress:
                    progress(f"Daily overwrite {db} → {sql_path}")
                with open(sql_path, "w", encoding="utf-8") as fh:
                    fh.write(f"-- MSSQL daily overwrite ({day}): {db}  Date: {datetime.now()}\n\n")
                    self._export_database(conn, db, fh, progress, tables_filter=tables)
                output_files.append(sql_path)
        finally:
            conn.close()

        if self.job.use_zip and output_files:
            return self._zip_daily(output_files, day, progress)
        return True, f"Daily overwrite ({day}) — {len(output_files)} file(s)"

    # ------------------------------------------------------------- .bak format --

    def _run_bak(self, ts: str, progress: Optional[Callable]) -> Tuple[bool, str]:
        """Run BACKUP DATABASE ... TO DISK for each selected database."""
        try:
            conn = pyodbc.connect(_conn_str(self.job), timeout=10)
            conn.autocommit = True  # BACKUP DATABASE requires autocommit
        except Exception as e:
            return False, f"Connection failed: {e}"

        try:
            databases = self.job.databases or self._list_databases(conn)
            if not databases:
                return False, "No databases to back up"

            results: List[str] = []
            for db in databases:
                if self.job.output_type == "daily_overwrite":
                    day = _DAYS[datetime.now().weekday()]
                    fname = f"{_safe_name(self.job.name)}_{_safe_name(db)}_{day}.bak"
                else:
                    fname = f"{_safe_name(self.job.name)}_{_safe_name(db)}_{ts}.bak"
                bak_path = os.path.normpath(os.path.join(self.job.output_dir, fname))

                if progress:
                    progress(f"BACKUP DATABASE [{db}] → {bak_path} …")

                ok, msg = self._backup_database_bak(conn, db, bak_path)
                if not ok:
                    return False, msg
                results.append(bak_path)

            return True, f"Backup complete — {len(results)} .bak file(s)"
        finally:
            conn.close()

    def _backup_database_bak(self, conn, db: str, bak_path: str) -> Tuple[bool, str]:
        safe_path = bak_path.replace("'", "''")
        safe_db = db.replace("]", "]]")
        sql = (
            f"BACKUP DATABASE [{safe_db}] "
            f"TO DISK = N'{safe_path}' "
            f"WITH INIT, NAME = N'{_safe_name(db)} backup', STATS = 10"
        )
        if self.job.use_zip:
            sql += ", COMPRESSION"
        try:
            cursor = conn.cursor()
            cursor.execute(sql)
            # Drain informational result sets SQL Server may send
            while True:
                try:
                    if not cursor.nextset():
                        break
                except Exception:
                    break
            return True, bak_path
        except Exception as e:
            msg = str(e)
            if "error 3(" in msg or "error 5(" in msg:
                msg += (
                    f"\n\nHint: The directory '{os.path.dirname(bak_path)}' must already "
                    "exist on the SQL Server machine and the SQL Server service account "
                    "must have write permission to it."
                )
            return False, f"BACKUP DATABASE [{db}] failed: {msg}"

    # ----------------------------------------------------------------- core --

    def _list_databases(self, conn) -> List[str]:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT name FROM sys.databases "
            "WHERE state_desc='ONLINE' AND name NOT IN ('master','tempdb','model','msdb') "
            "ORDER BY name"
        )
        return [r[0] for r in cursor.fetchall()]

    def _export_database(
        self,
        conn,
        db: str,
        fh,
        progress: Optional[Callable],
        tables_filter: List[str] = None,
    ):
        fh.write(f"USE [{db}];\nGO\n\n")

        db_conn = pyodbc.connect(_conn_str(self.job, db), timeout=10)
        try:
            cursor = db_conn.cursor()
            # Get all tables (schema.table format) in this database
            cursor.execute(
                "SELECT TABLE_SCHEMA, TABLE_NAME "
                "FROM INFORMATION_SCHEMA.TABLES "
                "WHERE TABLE_TYPE = 'BASE TABLE' "
                "ORDER BY TABLE_SCHEMA, TABLE_NAME"
            )
            all_tables = [(r[0], r[1]) for r in cursor.fetchall()]

            if tables_filter:
                # tables_filter contains "schema.table" or just "table"
                filtered = set()
                for tf in tables_filter:
                    if "." in tf:
                        filtered.add(tuple(tf.split(".", 1)))
                    else:
                        filtered.add(("dbo", tf))
                all_tables = [t for t in all_tables if t in filtered or (t[1],) in filtered]

            for schema, table in all_tables:
                if progress:
                    progress(f"  Scripting [{db}].[{schema}].[{table}] …")
                try:
                    fh.write(self._create_table_sql(db_conn, schema, table))
                    row_count = self._insert_data_sql(db_conn, schema, table, fh)
                    fh.write(f"-- {row_count} row(s) inserted into [{schema}].[{table}]\n\n")
                except Exception as e:
                    fh.write(f"-- ERROR scripting [{schema}].[{table}]: {e}\n\n")
        finally:
            db_conn.close()

    # ---------------------------------------------------- DDL / DML helpers --

    def _create_table_sql(self, conn, schema: str, table: str) -> str:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT
                c.COLUMN_NAME,
                c.DATA_TYPE,
                c.CHARACTER_MAXIMUM_LENGTH,
                c.NUMERIC_PRECISION,
                c.NUMERIC_SCALE,
                c.IS_NULLABLE,
                c.COLUMN_DEFAULT,
                COLUMNPROPERTY(OBJECT_ID(? + '.' + c.TABLE_NAME), c.COLUMN_NAME, 'IsIdentity') AS is_ident,
                IDENT_SEED(? + '.' + c.TABLE_NAME)  AS seed,
                IDENT_INCR(? + '.' + c.TABLE_NAME)  AS incr
            FROM INFORMATION_SCHEMA.COLUMNS c
            WHERE c.TABLE_NAME = ? AND c.TABLE_SCHEMA = ?
            ORDER BY c.ORDINAL_POSITION
        """, (schema, schema, schema, table, schema))

        col_defs = []
        for row in cursor.fetchall():
            col_name, dtype, char_len, prec, scale, nullable, default, is_ident, seed, incr = row

            # Build type string
            if dtype in ("varchar", "nvarchar", "char", "nchar", "varbinary", "binary"):
                type_str = f"{dtype}(MAX)" if char_len in (None, -1) else f"{dtype}({char_len})"
            elif dtype in ("decimal", "numeric"):
                type_str = f"{dtype}({prec},{scale})"
            elif dtype == "float":
                type_str = f"float({prec})" if prec else "float"
            else:
                type_str = dtype

            col_def = f"    [{col_name}] {type_str}"
            if is_ident:
                col_def += f" IDENTITY({int(seed or 1)},{int(incr or 1)})"
            if default:
                col_def += f" DEFAULT {default}"
            col_def += " NOT NULL" if nullable == "NO" else " NULL"
            col_defs.append(col_def)

        # Primary key
        cursor.execute("""
            SELECT ccu.COLUMN_NAME
            FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
            JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu
                ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
            WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
              AND tc.TABLE_NAME = ? AND tc.TABLE_SCHEMA = ?
            ORDER BY ccu.COLUMN_NAME
        """, (table, schema))
        pk_cols = [r[0] for r in cursor.fetchall()]
        if pk_cols:
            pk_str = ", ".join(f"[{c}]" for c in pk_cols)
            col_defs.append(f"    CONSTRAINT [PK_{table}] PRIMARY KEY ({pk_str})")

        sql = (
            f"IF OBJECT_ID(N'[{schema}].[{table}]', N'U') IS NOT NULL "
            f"DROP TABLE [{schema}].[{table}];\nGO\n"
            f"CREATE TABLE [{schema}].[{table}] (\n"
            + ",\n".join(col_defs)
            + "\n);\nGO\n\n"
        )
        return sql

    def _insert_data_sql(self, conn, schema: str, table: str, fh) -> int:
        cursor = conn.cursor()

        # Check for identity column
        cursor.execute(
            "SELECT COUNT(*) FROM sys.identity_columns ic "
            "JOIN sys.objects o ON ic.object_id = o.object_id "
            "JOIN sys.schemas s ON o.schema_id = s.schema_id "
            "WHERE o.name = ? AND s.name = ?",
            (table, schema),
        )
        has_identity = cursor.fetchone()[0] > 0

        cursor.execute(f"SELECT TOP 0 * FROM [{schema}].[{table}]")
        col_names = [col[0] for col in cursor.description]
        col_list = ", ".join(f"[{c}]" for c in col_names)

        if has_identity:
            fh.write(f"SET IDENTITY_INSERT [{schema}].[{table}] ON;\nGO\n")

        cursor.execute(f"SELECT * FROM [{schema}].[{table}]")
        row_count = 0
        for row in cursor:
            vals = []
            for val in row:
                if val is None:
                    vals.append("NULL")
                elif isinstance(val, bool):
                    vals.append("1" if val else "0")
                elif isinstance(val, int):
                    vals.append(str(val))
                elif isinstance(val, float):
                    vals.append(repr(val))
                elif isinstance(val, (bytes, bytearray)):
                    vals.append(f"0x{val.hex()}" if val else "0x")
                elif hasattr(val, "isoformat"):
                    vals.append(f"'{val.isoformat()}'")
                else:
                    vals.append("N'" + str(val).replace("'", "''") + "'")
            fh.write(
                f"INSERT INTO [{schema}].[{table}] ({col_list}) "
                f"VALUES ({', '.join(vals)});\n"
            )
            row_count += 1
            if row_count % 500 == 0:
                fh.write("GO\n")

        if has_identity:
            fh.write(f"SET IDENTITY_INSERT [{schema}].[{table}] OFF;\nGO\n")
        fh.write("GO\n")
        return row_count

    # ------------------------------------------------------------------ zip --

    def _zip_file(self, sql_path: str, progress: Optional[Callable]) -> Tuple[bool, str]:
        return self._zip_files([sql_path], datetime.now().strftime("%Y%m%d_%H%M%S"), progress)

    def _zip_files(
        self, sql_paths: List[str], ts: str, progress: Optional[Callable]
    ) -> Tuple[bool, str]:
        if progress:
            progress("Compressing …")
        try:
            import pyzipper
            name = _safe_name(self.job.name)
            arc = os.path.join(self.job.output_dir, f"{name}_{ts}.zip")
            with pyzipper.AESZipFile(arc, "w", compression=pyzipper.ZIP_DEFLATED,
                                     encryption=pyzipper.WZ_AES if self.job.zip_password else None) as zf:
                if self.job.zip_password:
                    zf.setpassword(self.job.zip_password.encode())
                for p in sql_paths:
                    zf.write(p, os.path.basename(p))
            for p in sql_paths:
                if os.path.exists(p):
                    os.remove(p)
            return True, f"Compressed: {arc}"
        except Exception as e:
            return True, f"Zip failed ({e}), SQL files kept in {self.job.output_dir}"

    def _zip_daily(
        self, sql_paths: List[str], day: str, progress: Optional[Callable]
    ) -> Tuple[bool, str]:
        if progress:
            progress("Compressing …")
        try:
            import pyzipper
            results = []
            for sql_path in sql_paths:
                arc = sql_path.replace(".sql", ".zip")
                with pyzipper.AESZipFile(arc, "w", compression=pyzipper.ZIP_DEFLATED,
                                         encryption=pyzipper.WZ_AES if self.job.zip_password else None) as zf:
                    if self.job.zip_password:
                        zf.setpassword(self.job.zip_password.encode())
                    zf.write(sql_path, os.path.basename(sql_path))
                if os.path.exists(sql_path):
                    os.remove(sql_path)
                results.append(arc)
            return True, f"Daily overwrite ({day}) compressed — {len(results)} file(s)"
        except Exception as e:
            return True, f"Zip failed ({e}), SQL files kept in {self.job.output_dir}"
